{
	"version": 1628188252,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/background-sheet0.png",
		"images/lives-sheet0.png",
		"images/sprite-sheet0.png",
		"images/p1-sheet0.png",
		"images/p1-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/cloud-sheet0.png",
		"images/clouds-sheet0.png",
		"images/waterdrops-sheet0.png",
		"images/waterdrops-sheet1.png",
		"images/waterdrops-sheet2.png",
		"images/water-sheet0.png",
		"images/mountains-sheet0.png",
		"images/sun-sheet0.png",
		"images/particles.png",
		"images/sprite2-sheet0.png",
		"media/click.m4a",
		"media/click.ogg",
		"media/lose.m4a",
		"media/lose.ogg",
		"media/water drop.m4a",
		"media/water drop.ogg",
		"media/water hit.m4a",
		"media/water hit.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}