const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.Sin,
		C3.Behaviors.scrollto,
		C3.Plugins.Touch,
		C3.Behaviors.Bullet,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Behaviors.Rotate,
		C3.Plugins.Mouse,
		C3.Plugins.AJAX,
		C3.Plugins.XML,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Behaviors.jumpthru,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.ScriptsInEvents.Events_home_Event70_Act1,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.XML.Acts.Load,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.XML.Exps.StringValue,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{sky_01: 0},
	{mountain_jas_01: 0},
	{mountain_jas_02: 0},
	{mountain_jas_03: 0},
	{mountain_jas_04: 0},
	{mountain_jas_05: 0},
	{mountain_pion_01: 0},
	{mountain_pion_02: 0},
	{mountain_pion_03: 0},
	{mountain_pion_04: 0},
	{mountain_pion_05: 0},
	{Solid: 0},
	{bridge_01: 0},
	{Platform: 0},
	{cat: 0},
	{stone_orange_big: 0},
	{stone_orange_small: 0},
	{stone_purple_big: 0},
	{stone_purple_small: 0},
	{stone_orange_horizontal: 0},
	{Sine: 0},
	{stone_mobile_horizontal: 0},
	{stone_mobile_vertical: 0},
	{stone_purple_horizontal: 0},
	{ScrollTo: 0},
	{element_cat: 0},
	{check: 0},
	{Touch: 0},
	{direction: 0},
	{fly: 0},
	{countt: 0},
	{Bullet: 0},
	{bird: 0},
	{mousee: 0},
	{key: 0},
	{door_start: 0},
	{cat_scarf: 0},
	{element_key: 0},
	{element_mouse: 0},
	{element_bird: 0},
	{element_limit: 0},
	{door: 0},
	{cloud_01_a: 0},
	{cloud_01_b: 0},
	{cloud_01_c: 0},
	{cloud_01_d: 0},
	{cloud_01_e: 0},
	{game_level_board: 0},
	{font_game_level: 0},
	{thorn_01: 0},
	{home_bg: 0},
	{level: 0},
	{levels_bt: 0},
	{levels_icon_mouse: 0},
	{levels_icon_bird: 0},
	{SpriteFont: 0},
	{info_bt_pause: 0},
	{info_bg: 0},
	{info_bt_play: 0},
	{info_bt_restart: 0},
	{info_bt_sound: 0},
	{info_bt_menu: 0},
	{Audio: 0},
	{Rotate: 0},
	{effect_dust: 0},
	{effect_blow: 0},
	{effect_element: 0},
	{effect_red: 0},
	{effect_white: 0},
	{effect_explosion: 0},
	{effect_element_explosion: 0},
	{info_element_mouse: 0},
	{info_element_bird: 0},
	{snowball_logo: 0},
	{home_bt_play: 0},
	{Mouse: 0},
	{tutorial: 0},
	{share_facebook: 0},
	{share_twitter: 0},
	{AJAX: 0},
	{XML: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{TextInput: 0},
	{Sprite: 0},
	{Username: 0},
	{TextInput2: 0},
	{Email: 0},
	{password: 0},
	{UserText: 0},
	{stones_purple: 0},
	{Jumpthru: 0},
	{mountains: 0},
	{stones: 0},
	{stones_mobile: 0},
	{info: 0},
	{level_now: 0},
	{game: 0},
	{cat_life: 0},
	{cat_run: 0},
	{cat_jump: 0},
	{cat_direction: 0},
	{check_ready: 0},
	{level_mouse_now: 0},
	{level_bird_now: 0},
	{level1: 0},
	{level2: 0},
	{level3: 0},
	{level4: 0},
	{level5: 0},
	{level6: 0},
	{level7: 0},
	{level8: 0},
	{level9: 0},
	{level10: 0},
	{level11: 0},
	{level12: 0},
	{level13: 0},
	{level14: 0},
	{level15: 0},
	{level16: 0},
	{level17: 0},
	{level18: 0},
	{level19: 0},
	{level20: 0},
	{level1_bird: 0},
	{level2_bird: 0},
	{level3_bird: 0},
	{level4_bird: 0},
	{level5_bird: 0},
	{level6_bird: 0},
	{level7_bird: 0},
	{level8_bird: 0},
	{level9_bird: 0},
	{level10_bird: 0},
	{level11_bird: 0},
	{level12_bird: 0},
	{level13_bird: 0},
	{level14_bird: 0},
	{level15_bird: 0},
	{level16_bird: 0},
	{level17_bird: 0},
	{level18_bird: 0},
	{level19_bird: 0},
	{level20_bird: 0},
	{level1_mouse: 0},
	{level2_mouse: 0},
	{level3_mouse: 0},
	{level4_mouse: 0},
	{level5_mouse: 0},
	{level6_mouse: 0},
	{level7_mouse: 0},
	{level8_mouse: 0},
	{level9_mouse: 0},
	{level10_mouse: 0},
	{level11_mouse: 0},
	{level12_mouse: 0},
	{level13_mouse: 0},
	{level14_mouse: 0},
	{level15_mouse: 0},
	{level16_mouse: 0},
	{level17_mouse: 0},
	{level18_mouse: 0},
	{level19_mouse: 0},
	{level20_mouse: 0},
	{UserGlobalVar: 0},
	{detect_mouse: 0},
	{facebookShare: 0},
	{facebook_message: 0},
	{twitterShare: 0},
	{twitter_message: 0}
];

self.InstanceType = {
	sky_01: class extends self.ISpriteInstance {},
	mountain_jas_01: class extends self.ISpriteInstance {},
	mountain_jas_02: class extends self.ISpriteInstance {},
	mountain_jas_03: class extends self.ISpriteInstance {},
	mountain_jas_04: class extends self.ISpriteInstance {},
	mountain_jas_05: class extends self.ISpriteInstance {},
	mountain_pion_01: class extends self.ISpriteInstance {},
	mountain_pion_02: class extends self.ISpriteInstance {},
	mountain_pion_03: class extends self.ISpriteInstance {},
	mountain_pion_04: class extends self.ISpriteInstance {},
	mountain_pion_05: class extends self.ISpriteInstance {},
	bridge_01: class extends self.ISpriteInstance {},
	cat: class extends self.ISpriteInstance {},
	stone_orange_big: class extends self.ISpriteInstance {},
	stone_orange_small: class extends self.ISpriteInstance {},
	stone_purple_big: class extends self.ISpriteInstance {},
	stone_purple_small: class extends self.ISpriteInstance {},
	stone_orange_horizontal: class extends self.ISpriteInstance {},
	stone_mobile_horizontal: class extends self.ISpriteInstance {},
	stone_mobile_vertical: class extends self.ISpriteInstance {},
	stone_purple_horizontal: class extends self.ISpriteInstance {},
	element_cat: class extends self.ISpriteInstance {},
	check: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	bird: class extends self.ISpriteInstance {},
	mousee: class extends self.ISpriteInstance {},
	key: class extends self.ISpriteInstance {},
	door_start: class extends self.ISpriteInstance {},
	cat_scarf: class extends self.ISpriteInstance {},
	element_key: class extends self.ISpriteInstance {},
	element_mouse: class extends self.ISpriteInstance {},
	element_bird: class extends self.ISpriteInstance {},
	element_limit: class extends self.ISpriteInstance {},
	door: class extends self.ISpriteInstance {},
	cloud_01_a: class extends self.ISpriteInstance {},
	cloud_01_b: class extends self.ISpriteInstance {},
	cloud_01_c: class extends self.ISpriteInstance {},
	cloud_01_d: class extends self.ISpriteInstance {},
	cloud_01_e: class extends self.ISpriteInstance {},
	game_level_board: class extends self.ISpriteInstance {},
	font_game_level: class extends self.ISpriteFontInstance {},
	thorn_01: class extends self.ISpriteInstance {},
	home_bg: class extends self.ISpriteInstance {},
	levels_bt: class extends self.ISpriteInstance {},
	levels_icon_mouse: class extends self.ISpriteInstance {},
	levels_icon_bird: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	info_bt_pause: class extends self.ISpriteInstance {},
	info_bg: class extends self.ISpriteInstance {},
	info_bt_play: class extends self.ISpriteInstance {},
	info_bt_restart: class extends self.ISpriteInstance {},
	info_bt_sound: class extends self.ISpriteInstance {},
	info_bt_menu: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	effect_dust: class extends self.ISpriteInstance {},
	effect_blow: class extends self.ISpriteInstance {},
	effect_element: class extends self.ISpriteInstance {},
	effect_red: class extends self.ISpriteInstance {},
	effect_white: class extends self.ISpriteInstance {},
	effect_explosion: class extends self.ISpriteInstance {},
	effect_element_explosion: class extends self.ISpriteInstance {},
	info_element_mouse: class extends self.ISpriteInstance {},
	info_element_bird: class extends self.ISpriteInstance {},
	snowball_logo: class extends self.ISpriteInstance {},
	home_bt_play: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	tutorial: class extends self.ISpriteInstance {},
	share_facebook: class extends self.ISpriteInstance {},
	share_twitter: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	XML: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Username: class extends self.ITextInputInstance {},
	TextInput2: class extends self.ITextInputInstance {},
	Email: class extends self.ITextInstance {},
	password: class extends self.ITextInputInstance {},
	UserText: class extends self.ITextInstance {},
	stones_purple: class extends self.ISpriteInstance {},
	mountains: class extends self.ISpriteInstance {},
	stones: class extends self.ISpriteInstance {},
	stones_mobile: class extends self.ISpriteInstance {},
	info: class extends self.ISpriteInstance {}
}