const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Spritefont2.Exps.LayerName,
		C3.Plugins.Spritefont2.Exps.Height,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Spritefont2.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.LocalStorage.Cnds.IsProcessingGets,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetPosToObject,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Exps.originalwindowheight,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Exps.originalwindowwidth,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{Mouse: 0},
	{Audio: 0},
	{Active: 0},
	{Original_Width: 0},
	{Original_Height: 0},
	{Name: 0},
	{Button_Exit: 0},
	{Button_Fullscreen: 0},
	{Button_More_Games: 0},
	{Button_Music: 0},
	{Button_Play: 0},
	{Button_Sound: 0},
	{Button_Start: 0},
	{Button_Menu: 0},
	{Button_Reload: 0},
	{Button_Return: 0},
	{Button_Pause: 0},
	{Button_Restart: 0},
	{Button_Facebook: 0},
	{Button_Twitter: 0},
	{Button_Level: 0},
	{Orientation_Font: 0},
	{Loading_Font: 0},
	{Top_Score_Font: 0},
	{Score_Font: 0},
	{Game_Score_Font: 0},
	{Distances_Font: 0},
	{Fuel_Font: 0},
	{Text_Paused: 0},
	{Fade: 0},
	{Text_Game_Over: 0},
	{Text_Ready: 0},
	{Text_You_Score: 0},
	{Text_Levels: 0},
	{Tween: 0},
	{Text_Go: 0},
	{Text_Out_Of_Fuel: 0},
	{Distances_UI: 0},
	{Coin_UI: 0},
	{Lives_UI: 0},
	{Height_Size: 0},
	{Fuel_UI: 0},
	{Fuel_UI_Mask: 0},
	{Game_Icon: 0},
	{Game_Logo: 0},
	{Rotate: 0},
	{Sun_Rays: 0},
	{Background: 0},
	{Background_Objects: 0},
	{Coin: 0},
	{Heart: 0},
	{Sine: 0},
	{Mace: 0},
	{Mountains_1: 0},
	{Mountains_2: 0},
	{Mountains_3: 0},
	{Pillar_Bottom: 0},
	{Pillar_Top: 0},
	{Platform: 0},
	{Flash: 0},
	{Player: 0},
	{Water: 0},
	{Extra: 0},
	{Fuel: 0},
	{Mirrored: 0},
	{Background_Player: 0},
	{Bomb: 0},
	{Background_Main_Sky_Left: 0},
	{Background_Main_Sky_Right: 0},
	{Magnet: 0},
	{Boost: 0},
	{Clouds: 0},
	{Gravity: 0},
	{Pin: 0},
	{Player_Magnet: 0},
	{Explosion: 0},
	{Speed_Effect: 0},
	{Fire: 0},
	{Percent_Size: 0},
	{Width_Size: 0},
	{Jetpack_Smoke: 0},
	{Dust: 0},
	{Hit_Effect: 0},
	{Buttons: 0},
	{Texts: 0},
	{Tween_Sprites: 0},
	{Tween_Fonts: 0},
	{Backgrounds: 0},
	{Objects: 0},
	{Effects: 0},
	{Sound: 0},
	{Sound_Status: 0},
	{Music: 0},
	{Music_Status: 0},
	{Fullscreen: 0},
	{Distance_Between_Objects: 0},
	{Game_Status: 0},
	{Game_Speed: 0},
	{Min_Game_Speed: 0},
	{Lives: 0},
	{Score: 0},
	{Top_Score: 0},
	{Count_Score: 0},
	{Distances: 0},
	{Coin_Size: 0},
	{Coin_Distance: 0},
	{Spawn: 0},
	{Spawn_Timer: 0},
	{Spawn_Object: 0},
	{Path_Difficulty: 0},
	{Max_Fuel: 0},
	{Fuel_Consumption: 0},
	{DESCRIPTION: 0},
	{REDIRECT_URL: 0},
	{IMAGE: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Button_Exit: class extends self.ISpriteInstance {},
	Button_Fullscreen: class extends self.ISpriteInstance {},
	Button_More_Games: class extends self.ISpriteInstance {},
	Button_Music: class extends self.ISpriteInstance {},
	Button_Play: class extends self.ISpriteInstance {},
	Button_Sound: class extends self.ISpriteInstance {},
	Button_Start: class extends self.ISpriteInstance {},
	Button_Menu: class extends self.ISpriteInstance {},
	Button_Reload: class extends self.ISpriteInstance {},
	Button_Return: class extends self.ISpriteInstance {},
	Button_Pause: class extends self.ISpriteInstance {},
	Button_Restart: class extends self.ISpriteInstance {},
	Button_Facebook: class extends self.ISpriteInstance {},
	Button_Twitter: class extends self.ISpriteInstance {},
	Button_Level: class extends self.ISpriteInstance {},
	Orientation_Font: class extends self.ISpriteFontInstance {},
	Loading_Font: class extends self.ISpriteFontInstance {},
	Top_Score_Font: class extends self.ISpriteFontInstance {},
	Score_Font: class extends self.ISpriteFontInstance {},
	Game_Score_Font: class extends self.ISpriteFontInstance {},
	Distances_Font: class extends self.ISpriteFontInstance {},
	Fuel_Font: class extends self.ISpriteFontInstance {},
	Text_Paused: class extends self.ISpriteInstance {},
	Text_Game_Over: class extends self.ISpriteInstance {},
	Text_Ready: class extends self.ISpriteInstance {},
	Text_You_Score: class extends self.ISpriteInstance {},
	Text_Levels: class extends self.ISpriteInstance {},
	Text_Go: class extends self.ISpriteInstance {},
	Text_Out_Of_Fuel: class extends self.ISpriteInstance {},
	Distances_UI: class extends self.ISpriteInstance {},
	Coin_UI: class extends self.ISpriteInstance {},
	Lives_UI: class extends self.ISpriteInstance {},
	Fuel_UI: class extends self.ISpriteInstance {},
	Fuel_UI_Mask: class extends self.ITiledBackgroundInstance {},
	Game_Icon: class extends self.ISpriteInstance {},
	Game_Logo: class extends self.ISpriteInstance {},
	Sun_Rays: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Background_Objects: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	Heart: class extends self.ISpriteInstance {},
	Mace: class extends self.ISpriteInstance {},
	Mountains_1: class extends self.ITiledBackgroundInstance {},
	Mountains_2: class extends self.ITiledBackgroundInstance {},
	Mountains_3: class extends self.ITiledBackgroundInstance {},
	Pillar_Bottom: class extends self.ISpriteInstance {},
	Pillar_Top: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Water: class extends self.ITiledBackgroundInstance {},
	Extra: class extends self.ISpriteInstance {},
	Fuel: class extends self.ISpriteInstance {},
	Background_Player: class extends self.ISpriteInstance {},
	Bomb: class extends self.ISpriteInstance {},
	Background_Main_Sky_Left: class extends self.ISpriteInstance {},
	Background_Main_Sky_Right: class extends self.ISpriteInstance {},
	Magnet: class extends self.ISpriteInstance {},
	Boost: class extends self.ISpriteInstance {},
	Clouds: class extends self.ISpriteInstance {},
	Player_Magnet: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	Speed_Effect: class extends self.ISpriteInstance {},
	Fire: class extends self.ISpriteInstance {},
	Jetpack_Smoke: class extends self.ISpriteInstance {},
	Dust: class extends self.ISpriteInstance {},
	Hit_Effect: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Texts: class extends self.ISpriteInstance {},
	Tween_Sprites: class extends self.ISpriteInstance {},
	Tween_Fonts: class extends self.ISpriteFontInstance {},
	Backgrounds: class extends self.ITiledBackgroundInstance {},
	Objects: class extends self.ISpriteInstance {},
	Effects: class extends self.ISpriteInstance {}
}